NONE equ 0

; Prims
PRIM_POINTS equ 0
PRIM_LINES equ 1
PRIM_LINE_STRIP equ 2
PRIM_TRIANGLES equ 3
PRIM_TRIANGLE_STRIP equ 4
PRIM_TRIANGLE_FAN equ 5
PRIM_RECTANGLES equ 6


; Vertex type options
VTYPE_WEIGHT_NONE equ 0
VTYPE_WEIGHT_U8 equ 1
VTYPE_WEIGHT_U16 equ 2
VTYPE_WEIGHT_F equ 3

VTYPE_TEXTURE_NONE equ 0
VTYPE_TEXTURE_U8 equ 1
VTYPE_TEXTURE_U16 equ 2
VTYPE_TEXTURE_F equ 3

VTYPE_COLOR_NONE equ 0
VTYPE_COLOR_RGB565 equ 4
VTYPE_COLOR_RGBA5 equ 5
VTYPE_COLOR_RGBA4 equ 6
VTYPE_COLOR_RGBA8 equ 7

VTYPE_NORMALS_NONE equ 0
VTYPE_NORMALS_S8 equ 1
VTYPE_NORMALS_S16 equ 2
VTYPE_NORMALS_F equ 3

VTYPE_POSITION_NONE equ 0
VTYPE_POSITION_S8 equ 1
VTYPE_POSITION_S16 equ 2
VTYPE_POSITION_F equ 3

VTYPE_INDEX_NONE equ 0
VTYPE_INDEX_U8 equ 1
VTYPE_INDEX_U16 equ 2
VTYPE_INDEX_U32 equ 3


; Texture Functions
TFUNC_MODULATE equ 0
TFUNC_DECAL equ 1
TFUNC_BLEND equ 2
TFUNC_REPLACE equ 3
TFUNC_ADD equ 4
TFUNC_ADD2 equ 5
TFUNC_ADD3 equ 6
TFUNC_ADD4 equ 7


; Texture pixel formats
TPF_5650 equ 0
TPF_5551 equ 1
TPF_4444 equ 2
TPF_8888 equ 3
TPF_CLUT4 equ 4
TPF_CLUT8 equ 5
TPF_CLUT16 equ 6
TPF_CLUT32 equ 7
TPF_DXT1 equ 8
TPF_DXT3 equ 9
TPF_DXT5 equ 0xA

; Alpha test operators
ATEST_NEVER equ 0
ATEST_ALWAYS equ 1
ATEST_EQUALS equ 2
ATEST_NOT_EQUAL equ 3
ATEST_LESS_THAN equ 4
ATEST_LESS_OR_EQUAL equ 5
ATEST_GREATER_THAN equ 6
ATEST_GREATER_OR_EQUAL equ 7

; Texture filters
TFILTER_NEARSET equ 0
TFILTER_LINEAR equ 1

; Texture filter attributes
TFILTER_ATTR_MIPMAP_NEARSET equ 4
TFILTER_ATTR_MIPMAP_LINEAR equ 6
